describe('TASK 4 - CHATBOT CHALLENGE', () => {
    it('First conversation', () => {
        cy.visit('https://www.cleverbot.com/')
        cy.get('#noteb > form > input').click()
        cy.get('.stimulus').click().type('Hi, how Are you??').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Can You tell me the capital city of Lithuania?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('The capital city of Lithuania is Vilnius. Do you know where is Lithuania?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Lithuania is in Eastern Europe').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Where is Mars??').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Do you know who is Jebus???').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Jebus is a character in Simpsons').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('I like Simpsons, Do you like Simpsons?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Do you know Elon Musk').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Nise to be a friend os Elon Musk...').type('{enter}')
    })
    it('Second conversation', () => {
        cy.visit('https://www.cleverbot.com/')
        cy.get('#noteb > form > input').click()
        cy.get('.stimulus').click().type('what time is now').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Do you know who is Donald Trump?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('As we all know he Was US President').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('do you know When Donald trump was born?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('donald trump was born in 1963 in USA').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Can you tell the diferences between Donald Trump and Apple?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Apple cant be a president. ha ha ha it was a joke').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Do you want another joke?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('Who is stronger than Spiderman?').type('{enter}')
        cy.wait(2000)
        cy.get('.stimulus').click().type('the answer is - Chuck Norris').type('{enter}')
        cy.wait(2000)
    })
})