describe('test', () => {
    it('should be able to visit home page', () => {
        cy.visit('cypress/integration/problemsEM/javascript-drum-kit/src/index.html');
    });
    it('play', () => {
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(500)
        cy.get('body').trigger('keydown', { keyCode: 65, which: 65 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 75, which: 75 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(500)
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(400)
        cy.get('body').trigger('keydown', { keyCode: 65, which: 65 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(900)
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 70, which: 70 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(400)
        cy.get('body').trigger('keydown', { keyCode: 68, which: 68 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(400)
        cy.get('body').trigger('keydown', { keyCode: 68, which: 68 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(400)
        cy.get('body').trigger('keydown', { keyCode: 70, which: 70 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(400)
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(500)
        cy.get('body').trigger('keydown', { keyCode: 65, which: 65 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 83, which: 83 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 68, which: 68 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(500)
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.get('body').trigger('keydown', { keyCode: 66, which: 66 })
        cy.get('body').trigger('keydown', { keyCode: 73, which: 73 })
        cy.wait(1000)
        cy.get('body').trigger('keydown', { keyCode: 74, which: 74 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(500)
        cy.get('body').trigger('keydown', { keyCode: 68, which: 68 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 75, which: 75 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 74, which: 74 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 74, which: 74 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 74, which: 74 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(400)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(1000)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(500)
        cy.get('body').trigger('keydown', { keyCode: 83, which: 83 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(700)
        cy.get('body').trigger('keydown', { keyCode: 74, which: 74 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(600)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 72, which: 72 })
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 71, which: 71 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.wait(300)
        cy.get('body').trigger('keydown', { keyCode: 86, which: 86 })
        cy.get('body').trigger('keydown', { keyCode: 82, which: 82 })
        cy.get('body').trigger('keydown', { keyCode: 66, which: 66 })
        cy.get('body').trigger('keydown', { keyCode: 73, which: 73 })

    })
});